title: IzzyDev`o
description: Let's automate!
author: Paweł Iżycki
github: https://github.com/pizycki
about: .NET developer, fan of automation and backend world.
disqus_shortname: izzydev
google_analytics: UA-93347392-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/pizycki"
    - icon: fa-twitter
      link: "https://twitter.com/pizycki"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/paweł-iżycki-5771a497"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/story/864968"
    - icon: fa-github
      link: "https://github.com/pizycki"

share:
  twitter_username: pizycki
  fb_appid: 1477315288968936

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "http://izzydev.net"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
